apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-node-service-ingress
  # namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "node-service.lowsandbox.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: 80
